project:
  type: website
  output-dir: docs

website:
  title: "Programming for Data Science"
  page-footer: 
    left: |
        Copyright 2024, Mutua Kilai <br> With inspiration from template created by [Andrew Heiss](https://www.andrewheiss.com/) 
    right: |
        Made with {{< fa brands r-project >}},<i class="fa-solid fa-heart"></i>, and [Quarto](https://quarto.org/)<br>
  navbar:
    background: "#ff9ee4"
    favicon: "images/imgfile.png"
    right:
      - href: index.qmd
        text: Course Description
      - href: contents/index.qmd
        text: Lecture Notes
      - href: assignments/index.qmd
        text: Assignments
      - href: announcements/index.qmd
        text: Announcements
      

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

