project:
  type: website
  render:
    - "*.qmd"
    - "!slides/"
  resources:
    - "slides/*.html"
    - "slides/*.pdf"
  output-dir: docs

website:
  title: "Programming for Data Science"
  favicon: "files/imgfile.png"
  page-footer: 
    left: |
        Copyright 2024, Mutua Kilai <br> With inspiration from template created by [Andrew Heiss](https://www.andrewheiss.com/) 
    right: |
        Made with {{< fa brands r-project >}},<i class="fa-solid fa-heart"></i>, and [Quarto](https://quarto.org/)<br>
  navbar:
    background: "#ff9ee4"
    pinned: true
    right:
      - text: "Course Description"
        file: index.qmd
      - text: "Lecture Notes"
        file: content/index.qmd
      - text: "Assignments"
        file: assignments/index.qmd
      - text: "Announcements"
        file: announcements/index.qmd
  page-navigation: true
  sidebar: 
    - title: "Introduction"
      style: "docked"
      background: light
      contents:
        - section: "Overview"
          contents:
            - content/index.qmd
        - section: "Lessons"
          contents: 
            - text: "Lesson 1: Introduction to Programming"
              file:  content/content01.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

